/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogoutImport } from './routes/logout'
import { Route as DashboardDashboardClientsIndexImport } from './routes/_dashboard/dashboard/clients/index'
import { Route as DashboardDashboardProjectsFoundationProjectIdImport } from './routes/_dashboard/dashboard/projects/foundation.$projectId'
import { Route as DashboardDashboardProjectsEditProjectIdImport } from './routes/_dashboard/dashboard/projects/edit.$projectId'
import { Route as DashboardDashboardClientsEditClientIdImport } from './routes/_dashboard/dashboard/clients/edit.$clientId'

// Create Virtual Routes

const LandingLazyImport = createFileRoute('/_landing')()
const DashboardLazyImport = createFileRoute('/_dashboard')()
const LandingIndexLazyImport = createFileRoute('/_landing/')()
const LandingServicesLazyImport = createFileRoute('/_landing/services')()
const LandingContactLazyImport = createFileRoute('/_landing/contact')()
const LandingAboutLazyImport = createFileRoute('/_landing/about')()
const DashboardDashboardIndexLazyImport = createFileRoute(
  '/_dashboard/dashboard/',
)()
const DashboardDashboardTimesheetLazyImport = createFileRoute(
  '/_dashboard/dashboard/timesheet',
)()
const DashboardDashboardScheduleLazyImport = createFileRoute(
  '/_dashboard/dashboard/schedule',
)()
const DashboardDashboardReportsLazyImport = createFileRoute(
  '/_dashboard/dashboard/reports',
)()
const DashboardDashboardProjectsIndexLazyImport = createFileRoute(
  '/_dashboard/dashboard/projects/',
)()
const DashboardDashboardMessagesIndexLazyImport = createFileRoute(
  '/_dashboard/dashboard/messages/',
)()
const DashboardDashboardEmployeesIndexLazyImport = createFileRoute(
  '/_dashboard/dashboard/employees/',
)()
const DashboardDashboardProjectsCreateLazyImport = createFileRoute(
  '/_dashboard/dashboard/projects/create',
)()
const DashboardDashboardEmployeesEmployeeIdLazyImport = createFileRoute(
  '/_dashboard/dashboard/employees/$employeeId',
)()
const DashboardDashboardClientsCreateLazyImport = createFileRoute(
  '/_dashboard/dashboard/clients/create',
)()

// Create/Update Routes

const LandingLazyRoute = LandingLazyImport.update({
  id: '/_landing',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_landing.lazy').then((d) => d.Route))

const DashboardLazyRoute = DashboardLazyImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_dashboard.lazy').then((d) => d.Route))

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LandingIndexLazyRoute = LandingIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingLazyRoute,
} as any).lazy(() =>
  import('./routes/_landing/index.lazy').then((d) => d.Route),
)

const LandingServicesLazyRoute = LandingServicesLazyImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LandingLazyRoute,
} as any).lazy(() =>
  import('./routes/_landing/services.lazy').then((d) => d.Route),
)

const LandingContactLazyRoute = LandingContactLazyImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LandingLazyRoute,
} as any).lazy(() =>
  import('./routes/_landing/contact.lazy').then((d) => d.Route),
)

const LandingAboutLazyRoute = LandingAboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LandingLazyRoute,
} as any).lazy(() =>
  import('./routes/_landing/about.lazy').then((d) => d.Route),
)

const DashboardDashboardIndexLazyRoute =
  DashboardDashboardIndexLazyImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/dashboard/index.lazy').then((d) => d.Route),
  )

const DashboardDashboardTimesheetLazyRoute =
  DashboardDashboardTimesheetLazyImport.update({
    id: '/dashboard/timesheet',
    path: '/dashboard/timesheet',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/dashboard/timesheet.lazy').then((d) => d.Route),
  )

const DashboardDashboardScheduleLazyRoute =
  DashboardDashboardScheduleLazyImport.update({
    id: '/dashboard/schedule',
    path: '/dashboard/schedule',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/dashboard/schedule.lazy').then((d) => d.Route),
  )

const DashboardDashboardReportsLazyRoute =
  DashboardDashboardReportsLazyImport.update({
    id: '/dashboard/reports',
    path: '/dashboard/reports',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/dashboard/reports.lazy').then((d) => d.Route),
  )

const DashboardDashboardProjectsIndexLazyRoute =
  DashboardDashboardProjectsIndexLazyImport.update({
    id: '/dashboard/projects/',
    path: '/dashboard/projects/',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/dashboard/projects/index.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardMessagesIndexLazyRoute =
  DashboardDashboardMessagesIndexLazyImport.update({
    id: '/dashboard/messages/',
    path: '/dashboard/messages/',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/dashboard/messages/index.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardEmployeesIndexLazyRoute =
  DashboardDashboardEmployeesIndexLazyImport.update({
    id: '/dashboard/employees/',
    path: '/dashboard/employees/',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/dashboard/employees/index.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardClientsIndexRoute =
  DashboardDashboardClientsIndexImport.update({
    id: '/dashboard/clients/',
    path: '/dashboard/clients/',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/dashboard/clients/index.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardProjectsCreateLazyRoute =
  DashboardDashboardProjectsCreateLazyImport.update({
    id: '/dashboard/projects/create',
    path: '/dashboard/projects/create',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/dashboard/projects/create.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardEmployeesEmployeeIdLazyRoute =
  DashboardDashboardEmployeesEmployeeIdLazyImport.update({
    id: '/dashboard/employees/$employeeId',
    path: '/dashboard/employees/$employeeId',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/dashboard/employees/$employeeId.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardClientsCreateLazyRoute =
  DashboardDashboardClientsCreateLazyImport.update({
    id: '/dashboard/clients/create',
    path: '/dashboard/clients/create',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/dashboard/clients/create.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardProjectsFoundationProjectIdRoute =
  DashboardDashboardProjectsFoundationProjectIdImport.update({
    id: '/dashboard/projects/foundation/$projectId',
    path: '/dashboard/projects/foundation/$projectId',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import(
      './routes/_dashboard/dashboard/projects/foundation.$projectId.lazy'
    ).then((d) => d.Route),
  )

const DashboardDashboardProjectsEditProjectIdRoute =
  DashboardDashboardProjectsEditProjectIdImport.update({
    id: '/dashboard/projects/edit/$projectId',
    path: '/dashboard/projects/edit/$projectId',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/dashboard/projects/edit.$projectId.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardClientsEditClientIdRoute =
  DashboardDashboardClientsEditClientIdImport.update({
    id: '/dashboard/clients/edit/$clientId',
    path: '/dashboard/clients/edit/$clientId',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/dashboard/clients/edit.$clientId.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingLazyImport
      parentRoute: typeof rootRoute
    }
    '/_landing/about': {
      id: '/_landing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LandingAboutLazyImport
      parentRoute: typeof LandingLazyImport
    }
    '/_landing/contact': {
      id: '/_landing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LandingContactLazyImport
      parentRoute: typeof LandingLazyImport
    }
    '/_landing/services': {
      id: '/_landing/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof LandingServicesLazyImport
      parentRoute: typeof LandingLazyImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexLazyImport
      parentRoute: typeof LandingLazyImport
    }
    '/_dashboard/dashboard/reports': {
      id: '/_dashboard/dashboard/reports'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardDashboardReportsLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/_dashboard/dashboard/schedule': {
      id: '/_dashboard/dashboard/schedule'
      path: '/dashboard/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof DashboardDashboardScheduleLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/_dashboard/dashboard/timesheet': {
      id: '/_dashboard/dashboard/timesheet'
      path: '/dashboard/timesheet'
      fullPath: '/dashboard/timesheet'
      preLoaderRoute: typeof DashboardDashboardTimesheetLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardIndexLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/_dashboard/dashboard/clients/create': {
      id: '/_dashboard/dashboard/clients/create'
      path: '/dashboard/clients/create'
      fullPath: '/dashboard/clients/create'
      preLoaderRoute: typeof DashboardDashboardClientsCreateLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/_dashboard/dashboard/employees/$employeeId': {
      id: '/_dashboard/dashboard/employees/$employeeId'
      path: '/dashboard/employees/$employeeId'
      fullPath: '/dashboard/employees/$employeeId'
      preLoaderRoute: typeof DashboardDashboardEmployeesEmployeeIdLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/_dashboard/dashboard/projects/create': {
      id: '/_dashboard/dashboard/projects/create'
      path: '/dashboard/projects/create'
      fullPath: '/dashboard/projects/create'
      preLoaderRoute: typeof DashboardDashboardProjectsCreateLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/_dashboard/dashboard/clients/': {
      id: '/_dashboard/dashboard/clients/'
      path: '/dashboard/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardDashboardClientsIndexImport
      parentRoute: typeof DashboardLazyImport
    }
    '/_dashboard/dashboard/employees/': {
      id: '/_dashboard/dashboard/employees/'
      path: '/dashboard/employees'
      fullPath: '/dashboard/employees'
      preLoaderRoute: typeof DashboardDashboardEmployeesIndexLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/_dashboard/dashboard/messages/': {
      id: '/_dashboard/dashboard/messages/'
      path: '/dashboard/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardDashboardMessagesIndexLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/_dashboard/dashboard/projects/': {
      id: '/_dashboard/dashboard/projects/'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardDashboardProjectsIndexLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/_dashboard/dashboard/clients/edit/$clientId': {
      id: '/_dashboard/dashboard/clients/edit/$clientId'
      path: '/dashboard/clients/edit/$clientId'
      fullPath: '/dashboard/clients/edit/$clientId'
      preLoaderRoute: typeof DashboardDashboardClientsEditClientIdImport
      parentRoute: typeof DashboardLazyImport
    }
    '/_dashboard/dashboard/projects/edit/$projectId': {
      id: '/_dashboard/dashboard/projects/edit/$projectId'
      path: '/dashboard/projects/edit/$projectId'
      fullPath: '/dashboard/projects/edit/$projectId'
      preLoaderRoute: typeof DashboardDashboardProjectsEditProjectIdImport
      parentRoute: typeof DashboardLazyImport
    }
    '/_dashboard/dashboard/projects/foundation/$projectId': {
      id: '/_dashboard/dashboard/projects/foundation/$projectId'
      path: '/dashboard/projects/foundation/$projectId'
      fullPath: '/dashboard/projects/foundation/$projectId'
      preLoaderRoute: typeof DashboardDashboardProjectsFoundationProjectIdImport
      parentRoute: typeof DashboardLazyImport
    }
  }
}

// Create and export the route tree

interface DashboardLazyRouteChildren {
  DashboardDashboardReportsLazyRoute: typeof DashboardDashboardReportsLazyRoute
  DashboardDashboardScheduleLazyRoute: typeof DashboardDashboardScheduleLazyRoute
  DashboardDashboardTimesheetLazyRoute: typeof DashboardDashboardTimesheetLazyRoute
  DashboardDashboardIndexLazyRoute: typeof DashboardDashboardIndexLazyRoute
  DashboardDashboardClientsCreateLazyRoute: typeof DashboardDashboardClientsCreateLazyRoute
  DashboardDashboardEmployeesEmployeeIdLazyRoute: typeof DashboardDashboardEmployeesEmployeeIdLazyRoute
  DashboardDashboardProjectsCreateLazyRoute: typeof DashboardDashboardProjectsCreateLazyRoute
  DashboardDashboardClientsIndexRoute: typeof DashboardDashboardClientsIndexRoute
  DashboardDashboardEmployeesIndexLazyRoute: typeof DashboardDashboardEmployeesIndexLazyRoute
  DashboardDashboardMessagesIndexLazyRoute: typeof DashboardDashboardMessagesIndexLazyRoute
  DashboardDashboardProjectsIndexLazyRoute: typeof DashboardDashboardProjectsIndexLazyRoute
  DashboardDashboardClientsEditClientIdRoute: typeof DashboardDashboardClientsEditClientIdRoute
  DashboardDashboardProjectsEditProjectIdRoute: typeof DashboardDashboardProjectsEditProjectIdRoute
  DashboardDashboardProjectsFoundationProjectIdRoute: typeof DashboardDashboardProjectsFoundationProjectIdRoute
}

const DashboardLazyRouteChildren: DashboardLazyRouteChildren = {
  DashboardDashboardReportsLazyRoute: DashboardDashboardReportsLazyRoute,
  DashboardDashboardScheduleLazyRoute: DashboardDashboardScheduleLazyRoute,
  DashboardDashboardTimesheetLazyRoute: DashboardDashboardTimesheetLazyRoute,
  DashboardDashboardIndexLazyRoute: DashboardDashboardIndexLazyRoute,
  DashboardDashboardClientsCreateLazyRoute:
    DashboardDashboardClientsCreateLazyRoute,
  DashboardDashboardEmployeesEmployeeIdLazyRoute:
    DashboardDashboardEmployeesEmployeeIdLazyRoute,
  DashboardDashboardProjectsCreateLazyRoute:
    DashboardDashboardProjectsCreateLazyRoute,
  DashboardDashboardClientsIndexRoute: DashboardDashboardClientsIndexRoute,
  DashboardDashboardEmployeesIndexLazyRoute:
    DashboardDashboardEmployeesIndexLazyRoute,
  DashboardDashboardMessagesIndexLazyRoute:
    DashboardDashboardMessagesIndexLazyRoute,
  DashboardDashboardProjectsIndexLazyRoute:
    DashboardDashboardProjectsIndexLazyRoute,
  DashboardDashboardClientsEditClientIdRoute:
    DashboardDashboardClientsEditClientIdRoute,
  DashboardDashboardProjectsEditProjectIdRoute:
    DashboardDashboardProjectsEditProjectIdRoute,
  DashboardDashboardProjectsFoundationProjectIdRoute:
    DashboardDashboardProjectsFoundationProjectIdRoute,
}

const DashboardLazyRouteWithChildren = DashboardLazyRoute._addFileChildren(
  DashboardLazyRouteChildren,
)

interface LandingLazyRouteChildren {
  LandingAboutLazyRoute: typeof LandingAboutLazyRoute
  LandingContactLazyRoute: typeof LandingContactLazyRoute
  LandingServicesLazyRoute: typeof LandingServicesLazyRoute
  LandingIndexLazyRoute: typeof LandingIndexLazyRoute
}

const LandingLazyRouteChildren: LandingLazyRouteChildren = {
  LandingAboutLazyRoute: LandingAboutLazyRoute,
  LandingContactLazyRoute: LandingContactLazyRoute,
  LandingServicesLazyRoute: LandingServicesLazyRoute,
  LandingIndexLazyRoute: LandingIndexLazyRoute,
}

const LandingLazyRouteWithChildren = LandingLazyRoute._addFileChildren(
  LandingLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/logout': typeof LogoutRoute
  '': typeof LandingLazyRouteWithChildren
  '/about': typeof LandingAboutLazyRoute
  '/contact': typeof LandingContactLazyRoute
  '/services': typeof LandingServicesLazyRoute
  '/': typeof LandingIndexLazyRoute
  '/dashboard/reports': typeof DashboardDashboardReportsLazyRoute
  '/dashboard/schedule': typeof DashboardDashboardScheduleLazyRoute
  '/dashboard/timesheet': typeof DashboardDashboardTimesheetLazyRoute
  '/dashboard': typeof DashboardDashboardIndexLazyRoute
  '/dashboard/clients/create': typeof DashboardDashboardClientsCreateLazyRoute
  '/dashboard/employees/$employeeId': typeof DashboardDashboardEmployeesEmployeeIdLazyRoute
  '/dashboard/projects/create': typeof DashboardDashboardProjectsCreateLazyRoute
  '/dashboard/clients': typeof DashboardDashboardClientsIndexRoute
  '/dashboard/employees': typeof DashboardDashboardEmployeesIndexLazyRoute
  '/dashboard/messages': typeof DashboardDashboardMessagesIndexLazyRoute
  '/dashboard/projects': typeof DashboardDashboardProjectsIndexLazyRoute
  '/dashboard/clients/edit/$clientId': typeof DashboardDashboardClientsEditClientIdRoute
  '/dashboard/projects/edit/$projectId': typeof DashboardDashboardProjectsEditProjectIdRoute
  '/dashboard/projects/foundation/$projectId': typeof DashboardDashboardProjectsFoundationProjectIdRoute
}

export interface FileRoutesByTo {
  '/logout': typeof LogoutRoute
  '': typeof DashboardLazyRouteWithChildren
  '/about': typeof LandingAboutLazyRoute
  '/contact': typeof LandingContactLazyRoute
  '/services': typeof LandingServicesLazyRoute
  '/': typeof LandingIndexLazyRoute
  '/dashboard/reports': typeof DashboardDashboardReportsLazyRoute
  '/dashboard/schedule': typeof DashboardDashboardScheduleLazyRoute
  '/dashboard/timesheet': typeof DashboardDashboardTimesheetLazyRoute
  '/dashboard': typeof DashboardDashboardIndexLazyRoute
  '/dashboard/clients/create': typeof DashboardDashboardClientsCreateLazyRoute
  '/dashboard/employees/$employeeId': typeof DashboardDashboardEmployeesEmployeeIdLazyRoute
  '/dashboard/projects/create': typeof DashboardDashboardProjectsCreateLazyRoute
  '/dashboard/clients': typeof DashboardDashboardClientsIndexRoute
  '/dashboard/employees': typeof DashboardDashboardEmployeesIndexLazyRoute
  '/dashboard/messages': typeof DashboardDashboardMessagesIndexLazyRoute
  '/dashboard/projects': typeof DashboardDashboardProjectsIndexLazyRoute
  '/dashboard/clients/edit/$clientId': typeof DashboardDashboardClientsEditClientIdRoute
  '/dashboard/projects/edit/$projectId': typeof DashboardDashboardProjectsEditProjectIdRoute
  '/dashboard/projects/foundation/$projectId': typeof DashboardDashboardProjectsFoundationProjectIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/logout': typeof LogoutRoute
  '/_dashboard': typeof DashboardLazyRouteWithChildren
  '/_landing': typeof LandingLazyRouteWithChildren
  '/_landing/about': typeof LandingAboutLazyRoute
  '/_landing/contact': typeof LandingContactLazyRoute
  '/_landing/services': typeof LandingServicesLazyRoute
  '/_landing/': typeof LandingIndexLazyRoute
  '/_dashboard/dashboard/reports': typeof DashboardDashboardReportsLazyRoute
  '/_dashboard/dashboard/schedule': typeof DashboardDashboardScheduleLazyRoute
  '/_dashboard/dashboard/timesheet': typeof DashboardDashboardTimesheetLazyRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexLazyRoute
  '/_dashboard/dashboard/clients/create': typeof DashboardDashboardClientsCreateLazyRoute
  '/_dashboard/dashboard/employees/$employeeId': typeof DashboardDashboardEmployeesEmployeeIdLazyRoute
  '/_dashboard/dashboard/projects/create': typeof DashboardDashboardProjectsCreateLazyRoute
  '/_dashboard/dashboard/clients/': typeof DashboardDashboardClientsIndexRoute
  '/_dashboard/dashboard/employees/': typeof DashboardDashboardEmployeesIndexLazyRoute
  '/_dashboard/dashboard/messages/': typeof DashboardDashboardMessagesIndexLazyRoute
  '/_dashboard/dashboard/projects/': typeof DashboardDashboardProjectsIndexLazyRoute
  '/_dashboard/dashboard/clients/edit/$clientId': typeof DashboardDashboardClientsEditClientIdRoute
  '/_dashboard/dashboard/projects/edit/$projectId': typeof DashboardDashboardProjectsEditProjectIdRoute
  '/_dashboard/dashboard/projects/foundation/$projectId': typeof DashboardDashboardProjectsFoundationProjectIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/logout'
    | ''
    | '/about'
    | '/contact'
    | '/services'
    | '/'
    | '/dashboard/reports'
    | '/dashboard/schedule'
    | '/dashboard/timesheet'
    | '/dashboard'
    | '/dashboard/clients/create'
    | '/dashboard/employees/$employeeId'
    | '/dashboard/projects/create'
    | '/dashboard/clients'
    | '/dashboard/employees'
    | '/dashboard/messages'
    | '/dashboard/projects'
    | '/dashboard/clients/edit/$clientId'
    | '/dashboard/projects/edit/$projectId'
    | '/dashboard/projects/foundation/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logout'
    | ''
    | '/about'
    | '/contact'
    | '/services'
    | '/'
    | '/dashboard/reports'
    | '/dashboard/schedule'
    | '/dashboard/timesheet'
    | '/dashboard'
    | '/dashboard/clients/create'
    | '/dashboard/employees/$employeeId'
    | '/dashboard/projects/create'
    | '/dashboard/clients'
    | '/dashboard/employees'
    | '/dashboard/messages'
    | '/dashboard/projects'
    | '/dashboard/clients/edit/$clientId'
    | '/dashboard/projects/edit/$projectId'
    | '/dashboard/projects/foundation/$projectId'
  id:
    | '__root__'
    | '/logout'
    | '/_dashboard'
    | '/_landing'
    | '/_landing/about'
    | '/_landing/contact'
    | '/_landing/services'
    | '/_landing/'
    | '/_dashboard/dashboard/reports'
    | '/_dashboard/dashboard/schedule'
    | '/_dashboard/dashboard/timesheet'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/clients/create'
    | '/_dashboard/dashboard/employees/$employeeId'
    | '/_dashboard/dashboard/projects/create'
    | '/_dashboard/dashboard/clients/'
    | '/_dashboard/dashboard/employees/'
    | '/_dashboard/dashboard/messages/'
    | '/_dashboard/dashboard/projects/'
    | '/_dashboard/dashboard/clients/edit/$clientId'
    | '/_dashboard/dashboard/projects/edit/$projectId'
    | '/_dashboard/dashboard/projects/foundation/$projectId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LogoutRoute: typeof LogoutRoute
  DashboardLazyRoute: typeof DashboardLazyRouteWithChildren
  LandingLazyRoute: typeof LandingLazyRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LogoutRoute: LogoutRoute,
  DashboardLazyRoute: DashboardLazyRouteWithChildren,
  LandingLazyRoute: LandingLazyRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/logout",
        "/_dashboard",
        "/_landing"
      ]
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/_dashboard": {
      "filePath": "_dashboard.lazy.tsx",
      "children": [
        "/_dashboard/dashboard/reports",
        "/_dashboard/dashboard/schedule",
        "/_dashboard/dashboard/timesheet",
        "/_dashboard/dashboard/",
        "/_dashboard/dashboard/clients/create",
        "/_dashboard/dashboard/employees/$employeeId",
        "/_dashboard/dashboard/projects/create",
        "/_dashboard/dashboard/clients/",
        "/_dashboard/dashboard/employees/",
        "/_dashboard/dashboard/messages/",
        "/_dashboard/dashboard/projects/",
        "/_dashboard/dashboard/clients/edit/$clientId",
        "/_dashboard/dashboard/projects/edit/$projectId",
        "/_dashboard/dashboard/projects/foundation/$projectId"
      ]
    },
    "/_landing": {
      "filePath": "_landing.lazy.tsx",
      "children": [
        "/_landing/about",
        "/_landing/contact",
        "/_landing/services",
        "/_landing/"
      ]
    },
    "/_landing/about": {
      "filePath": "_landing/about.lazy.tsx",
      "parent": "/_landing"
    },
    "/_landing/contact": {
      "filePath": "_landing/contact.lazy.tsx",
      "parent": "/_landing"
    },
    "/_landing/services": {
      "filePath": "_landing/services.lazy.tsx",
      "parent": "/_landing"
    },
    "/_landing/": {
      "filePath": "_landing/index.lazy.tsx",
      "parent": "/_landing"
    },
    "/_dashboard/dashboard/reports": {
      "filePath": "_dashboard/dashboard/reports.lazy.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/schedule": {
      "filePath": "_dashboard/dashboard/schedule.lazy.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/timesheet": {
      "filePath": "_dashboard/dashboard/timesheet.lazy.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/": {
      "filePath": "_dashboard/dashboard/index.lazy.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/clients/create": {
      "filePath": "_dashboard/dashboard/clients/create.lazy.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/employees/$employeeId": {
      "filePath": "_dashboard/dashboard/employees/$employeeId.lazy.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/projects/create": {
      "filePath": "_dashboard/dashboard/projects/create.lazy.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/clients/": {
      "filePath": "_dashboard/dashboard/clients/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/employees/": {
      "filePath": "_dashboard/dashboard/employees/index.lazy.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/messages/": {
      "filePath": "_dashboard/dashboard/messages/index.lazy.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/projects/": {
      "filePath": "_dashboard/dashboard/projects/index.lazy.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/clients/edit/$clientId": {
      "filePath": "_dashboard/dashboard/clients/edit.$clientId.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/projects/edit/$projectId": {
      "filePath": "_dashboard/dashboard/projects/edit.$projectId.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/projects/foundation/$projectId": {
      "filePath": "_dashboard/dashboard/projects/foundation.$projectId.tsx",
      "parent": "/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
