# Use the same base image for consistency
FROM oven/bun:1.1.38-slim

WORKDIR /app

# Copy package.json and bun.lockb to install dependencies
COPY ./package.json ./bun.lockb /app/

RUN apt update \
    && apt install -y curl


ARG NODE_VERSION=20

RUN curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n \
    && bash n $NODE_VERSION \
    && rm n \
    && npm install -g n


# Copy only the necessary directories
COPY . .

# Install dependencies

RUN npm rebuild argon2

RUN bun install

# Copy the rest of the application code


# Generate Prisma client
RUN bun run server:db-generate

# Expose the test port
EXPOSE 5001

# Default command (can be overridden in docker-compose)
ENTRYPOINT ["bun", "run", "server:dev"]