/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as LandingServicesRouteImport } from './routes/_landing/services'
import { Route as LandingContactRouteImport } from './routes/_landing/contact'
import { Route as LandingAboutRouteImport } from './routes/_landing/about'

const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingServicesRoute = LandingServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LandingRoute,
} as any)
const LandingContactRoute = LandingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LandingRoute,
} as any)
const LandingAboutRoute = LandingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LandingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/about': typeof LandingAboutRoute
  '/contact': typeof LandingContactRoute
  '/services': typeof LandingServicesRoute
}
export interface FileRoutesByTo {
  '/about': typeof LandingAboutRoute
  '/contact': typeof LandingContactRoute
  '/services': typeof LandingServicesRoute
  '/': typeof LandingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteWithChildren
  '/_landing/about': typeof LandingAboutRoute
  '/_landing/contact': typeof LandingContactRoute
  '/_landing/services': typeof LandingServicesRoute
  '/_landing/': typeof LandingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/services'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/contact' | '/services' | '/'
  id:
    | '__root__'
    | '/_landing'
    | '/_landing/about'
    | '/_landing/contact'
    | '/_landing/services'
    | '/_landing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRoute: typeof LandingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/services': {
      id: '/_landing/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof LandingServicesRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/contact': {
      id: '/_landing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LandingContactRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/about': {
      id: '/_landing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LandingAboutRouteImport
      parentRoute: typeof LandingRoute
    }
  }
}

interface LandingRouteChildren {
  LandingAboutRoute: typeof LandingAboutRoute
  LandingContactRoute: typeof LandingContactRoute
  LandingServicesRoute: typeof LandingServicesRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingAboutRoute: LandingAboutRoute,
  LandingContactRoute: LandingContactRoute,
  LandingServicesRoute: LandingServicesRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LandingRoute: LandingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
