/**
 * Pure reducer over the authored sheet document (JobSheetData). Breakdown
 * computation is NOT done here — the provider derives it with
 * computeJobSheet, so the reducer stays trivially testable.
 *
 * Ids are generated by the dispatch call sites (crypto.randomUUID), never
 * inside the reducer, to keep it pure.
 */

import {
  type JobSheetData,
  type SheetItem,
  type Wall,
  type WallOverride
} from '@dreams-built/shared/src/jobsheet/types';

export type SectionKey = 'joinery' | 'showerBoxes' | 'garage';

export const emptyWall = (id: string): Wall => ({
  id,
  lengthMm: 0,
  cornerStart: 'external',
  cornerEnd: 'external',
  absorbShutterAtStart: null,
  absorbShutterAtEnd: null,
  hasRebate: true,
  rebateOffsetAtStart: null,
  rebateOffsetAtEnd: null,
  rebateExtendAtStart: null,
  rebateExtendAtEnd: null,
  overhangCapAtEnd: null,
  blkAtStart: false,
  blkAtEnd: false,
  openings: [],
  rebateInsets: [],
  manualRuns: [],
  polystyreneOverride: null,
  angledCornerDeg: null,
  isGarageDoorWall: false,
  notes: '',
  override: null
});

const emptyItem = (id: string): SheetItem => ({ id, text: '', qty: null });

export type JobSheetAction =
  | { type: 'addWall'; id: string }
  | { type: 'updateWall'; id: string; patch: Partial<Wall> }
  | { type: 'removeWall'; id: string }
  | { type: 'moveWall'; from: number; to: number }
  | { type: 'setOverride'; id: string; override: WallOverride | null }
  | { type: 'addItem'; section: SectionKey; id: string }
  | { type: 'updateItem'; section: SectionKey; id: string; patch: Partial<SheetItem> }
  | { type: 'removeItem'; section: SectionKey; id: string }
  | { type: 'setNotes'; notes: string }
  | { type: 'setRebatesEnabled'; value: boolean }
  | { type: 'setMode'; value: 'auto' | 'manual' }
  | { type: 'setManualThirdColumn'; value: boolean }
  | { type: 'replaceAll'; data: JobSheetData };

export const jobSheetReducer = (
  state: JobSheetData,
  action: JobSheetAction
): JobSheetData => {
  switch (action.type) {
    case 'addWall':
      return { ...state, walls: [...state.walls, emptyWall(action.id)] };

    case 'updateWall': {
      const index = state.walls.findIndex((wall) => wall.id === action.id);
      if (index === -1) return state;
      const walls = state.walls.map((wall, i) =>
        i === index ? { ...wall, ...action.patch } : wall
      );

      // A corner is shared: wall i's end corner IS wall i+1's start corner
      // (wrapping last -> first around the perimeter). Keep both sides in
      // sync so the absorb toggles on either wall stay available, and drop
      // an absorb flag that no longer applies at an external corner.
      if (walls.length > 1 && action.patch.cornerEnd !== undefined) {
        const next = (index + 1) % walls.length;
        walls[next] = {
          ...walls[next],
          cornerStart: action.patch.cornerEnd,
          // Corner changed: fall back to auto so the convention re-applies.
          absorbShutterAtStart: null,
          rebateExtendAtStart: null,
          rebateOffsetAtStart: null
        };
      }
      if (walls.length > 1 && action.patch.cornerStart !== undefined) {
        const previous = (index - 1 + walls.length) % walls.length;
        walls[previous] = {
          ...walls[previous],
          cornerEnd: action.patch.cornerStart,
          absorbShutterAtEnd: null,
          rebateExtendAtEnd: null,
          rebateOffsetAtEnd: null,
          overhangCapAtEnd: null
        };
      }

      return { ...state, walls };
    }

    case 'removeWall':
      return { ...state, walls: state.walls.filter((wall) => wall.id !== action.id) };

    case 'moveWall': {
      const { from, to } = action;
      if (
        from === to ||
        from < 0 ||
        to < 0 ||
        from >= state.walls.length ||
        to >= state.walls.length
      ) {
        return state;
      }
      const walls = [...state.walls];
      const [moved] = walls.splice(from, 1);
      walls.splice(to, 0, moved);
      return { ...state, walls };
    }

    case 'setOverride':
      return {
        ...state,
        walls: state.walls.map((wall) =>
          wall.id === action.id ? { ...wall, override: action.override } : wall
        )
      };

    case 'addItem':
      return {
        ...state,
        [action.section]: [...state[action.section], emptyItem(action.id)]
      };

    case 'updateItem':
      return {
        ...state,
        [action.section]: state[action.section].map((item) =>
          item.id === action.id ? { ...item, ...action.patch } : item
        )
      };

    case 'removeItem':
      return {
        ...state,
        [action.section]: state[action.section].filter((item) => item.id !== action.id)
      };

    case 'setNotes':
      return { ...state, notes: action.notes };

    case 'setRebatesEnabled':
      return { ...state, rebatesEnabled: action.value };

    case 'setMode':
      return { ...state, mode: action.value };

    case 'setManualThirdColumn':
      return { ...state, manualThirdColumn: action.value };

    case 'replaceAll':
      return action.data;

    default:
      return state;
  }
};


/* ------------------------------------------------------------------ */
/* Undo / redo                                                          */
/* ------------------------------------------------------------------ */

export type HistoryAction = JobSheetAction | { type: 'undo' } | { type: 'redo' };

export type SheetHistory = {
  past: JobSheetData[];
  present: JobSheetData;
  future: JobSheetData[];
  /** Merge key of the previous edit, so typing coalesces into one step. */
  lastEdit: string | null;
};

const HISTORY_LIMIT = 50;

/** Consecutive edits with the same key merge into a single undo step. */
const editKey = (action: JobSheetAction): string | null => {
  switch (action.type) {
    case 'updateWall':
      return `updateWall:${action.id}:${Object.keys(action.patch).sort().join(',')}`;
    case 'updateItem':
      return `updateItem:${action.section}:${action.id}:${Object.keys(action.patch)
        .sort()
        .join(',')}`;
    case 'setNotes':
      return 'setNotes';
    default:
      return null;
  }
};

export const initialHistory = (present: JobSheetData): SheetHistory => ({
  past: [],
  present,
  future: [],
  lastEdit: null
});

export const historyReducer = (
  state: SheetHistory,
  action: HistoryAction
): SheetHistory => {
  if (action.type === 'undo') {
    if (state.past.length === 0) return state;
    const previous = state.past[state.past.length - 1];
    return {
      past: state.past.slice(0, -1),
      present: previous,
      future: [state.present, ...state.future],
      lastEdit: null
    };
  }
  if (action.type === 'redo') {
    if (state.future.length === 0) return state;
    const [next, ...rest] = state.future;
    return {
      past: [...state.past, state.present],
      present: next,
      future: rest,
      lastEdit: null
    };
  }

  const present = jobSheetReducer(state.present, action);
  if (present === state.present) return state;
  const key = editKey(action);
  const merge = key !== null && key === state.lastEdit;
  return {
    past: merge ? state.past : [...state.past.slice(-(HISTORY_LIMIT - 1)), state.present],
    present,
    future: [],
    lastEdit: key
  };
};
