/**
 * Pure reducer over the authored sheet document (JobSheetData). Breakdown
 * computation is NOT done here — the provider derives it with
 * computeJobSheet, so the reducer stays trivially testable.
 *
 * Ids are generated by the dispatch call sites (crypto.randomUUID), never
 * inside the reducer, to keep it pure.
 */

import {
  type JobSheetData,
  type SheetItem,
  type Wall,
  type WallOverride
} from '@dreams-built/shared/src/jobsheet/types';

export type SectionKey = 'joinery' | 'showerBoxes' | 'garage';

export const emptyWall = (id: string): Wall => ({
  id,
  lengthMm: 0,
  cornerStart: 'external',
  cornerEnd: 'external',
  absorbShutterAtStart: false,
  absorbShutterAtEnd: false,
  hasRebate: true,
  rebateOffsetAtStart: false,
  rebateOffsetAtEnd: false,
  blkAtStart: false,
  blkAtEnd: false,
  openings: [],
  polystyreneOverride: null,
  angledCornerDeg: null,
  isGarageDoorWall: false,
  notes: '',
  override: null
});

const emptyItem = (id: string): SheetItem => ({ id, text: '', qty: null });

export type JobSheetAction =
  | { type: 'addWall'; id: string }
  | { type: 'updateWall'; id: string; patch: Partial<Wall> }
  | { type: 'removeWall'; id: string }
  | { type: 'moveWall'; from: number; to: number }
  | { type: 'setOverride'; id: string; override: WallOverride | null }
  | { type: 'addItem'; section: SectionKey; id: string }
  | { type: 'updateItem'; section: SectionKey; id: string; patch: Partial<SheetItem> }
  | { type: 'removeItem'; section: SectionKey; id: string }
  | { type: 'setNotes'; notes: string }
  | { type: 'replaceAll'; data: JobSheetData };

export const jobSheetReducer = (
  state: JobSheetData,
  action: JobSheetAction
): JobSheetData => {
  switch (action.type) {
    case 'addWall':
      return { ...state, walls: [...state.walls, emptyWall(action.id)] };

    case 'updateWall': {
      const index = state.walls.findIndex((wall) => wall.id === action.id);
      if (index === -1) return state;
      const walls = state.walls.map((wall, i) =>
        i === index ? { ...wall, ...action.patch } : wall
      );

      // A corner is shared: wall i's end corner IS wall i+1's start corner
      // (wrapping last -> first around the perimeter). Keep both sides in
      // sync so the absorb toggles on either wall stay available, and drop
      // an absorb flag that no longer applies at an external corner.
      if (walls.length > 1 && action.patch.cornerEnd !== undefined) {
        const next = (index + 1) % walls.length;
        walls[next] = {
          ...walls[next],
          cornerStart: action.patch.cornerEnd,
          ...(action.patch.cornerEnd === 'external' && {
            absorbShutterAtStart: false
          })
        };
      }
      if (walls.length > 1 && action.patch.cornerStart !== undefined) {
        const previous = (index - 1 + walls.length) % walls.length;
        walls[previous] = {
          ...walls[previous],
          cornerEnd: action.patch.cornerStart,
          ...(action.patch.cornerStart === 'external' && {
            absorbShutterAtEnd: false
          })
        };
      }

      return { ...state, walls };
    }

    case 'removeWall':
      return { ...state, walls: state.walls.filter((wall) => wall.id !== action.id) };

    case 'moveWall': {
      const { from, to } = action;
      if (
        from === to ||
        from < 0 ||
        to < 0 ||
        from >= state.walls.length ||
        to >= state.walls.length
      ) {
        return state;
      }
      const walls = [...state.walls];
      const [moved] = walls.splice(from, 1);
      walls.splice(to, 0, moved);
      return { ...state, walls };
    }

    case 'setOverride':
      return {
        ...state,
        walls: state.walls.map((wall) =>
          wall.id === action.id ? { ...wall, override: action.override } : wall
        )
      };

    case 'addItem':
      return {
        ...state,
        [action.section]: [...state[action.section], emptyItem(action.id)]
      };

    case 'updateItem':
      return {
        ...state,
        [action.section]: state[action.section].map((item) =>
          item.id === action.id ? { ...item, ...action.patch } : item
        )
      };

    case 'removeItem':
      return {
        ...state,
        [action.section]: state[action.section].filter((item) => item.id !== action.id)
      };

    case 'setNotes':
      return { ...state, notes: action.notes };

    case 'replaceAll':
      return action.data;

    default:
      return state;
  }
};
